config/routes.rb
LssUsdlEditor::Application.routes.draw do

  resources :service_systems do

    resources :interactions do
      put "add_entity"
      delete "delete_entity"
      get "edit_time"
    end

    resources :business_entities
    resources :roles
    resources :goals
    resources :locations
    resources :process_entities, path: "processes"
    resources :resources

    get 'export_to_lss_usdl'
    get 'export_to_linked_usdl'

  end

  match "/service_systems/import" => "service_systems#import"

  devise_for :users

  root to: "service_systems#index"

end

app/models/process_entity.rb
class ProcessEntity < ActiveRecord::Base
  attr_accessible :comment, :label, :bpmn_uri, :service_system_id, :sid
  belongs_to :service_system
  has_and_belongs_to_many :interactions, class_name: "Interaction", join_table: "interactions_processes"

  validates :label, :sid, presence: true
  validates :service_system_id, numericality: { only_integer: true }

  def to_s
    self.label
  end
end

app/controllers/process_entities_controller.rb
class ProcessEntitiesController < ApplicationController
  before_filter :select_tab

  def index
    if @service_system.present?
      @process_entities = ProcessEntity.where "service_system_id = ?", @service_system.id
    else
      @process_entities = ProcessEntity.all
    end

    respond_to do |format|
      format.html
      format.json { render json: @process_entities }
    end
  end

  def show
    @process_entity = ProcessEntity.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @process_entity }
    end
  end

  def new
    @process_entity = @service_system.process_entities.build

    respond_to do |format|
      format.html
      format.json { render json: @process_entity }
    end
  end

  def edit
    @process_entity = ProcessEntity.find(params[:id])
  end

  def create
    @process_entity = ProcessEntity.new(params[:process_entity])
    @process_entity.sid = camel_case @process_entity.label
    @process_entity.service_system = @service_system if @service_system.present?

    respond_to do |format|
      if @process_entity.save
        format.html { redirect_to service_system_process_entities_url, notice: 'Process was successfully created.' }
        format.json { render json: @process_entity, status: :created, location: @process_entity }
      else
        format.html { render action: "new" }
        format.json { render json: @process_entity.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @process_entity = ProcessEntity.find(params[:id])
    params[:process_entity][:sid] = camel_case params[:process_entity][:label]

    respond_to do |format|
      if @process_entity.update_attributes(params[:process_entity])
        format.html { redirect_to service_system_process_entity_url, notice: 'Process was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @process_entity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @process_entity = ProcessEntity.find(params[:id])
    @process_entity.destroy

    respond_to do |format|
      format.html { redirect_to service_system_process_entities_url }
      format.json { head :no_content }
    end
  end

  private

  def select_tab
    @tab = {"processes" => true}
  end
end

app/helpers/process_entities_helper.rb
module ProcessEntitiesHelper
end

app/views/process_entities/_form.html.erb
<%= form_for [@service_system, @process_entity] do |f| %>

  <% if @process_entity.errors.any? %>
    <div id="error-explanation">
      <h4><%= pluralize @process_entity.errors.count, "error" %> prevented this process_entity from being saved:</h4>
      <ul>
      <% @process_entity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table>
  
    <tr>
      <td><%= f.label :label %></td>
      <td><%= f.text_field :label, class: "span5" %></td>
    </tr>

    <tr>
      <td><%= f.label :bpmn_uri, "URI of BPMN description" %></td>
      <td><%= f.text_field :bpmn_uri, class: "span5" %></td>
    </tr>
  
    <tr>
      <td><%= f.label :comment %></td>
      <td><%= f.text_area :comment, class: "span5", rows: "3" %></td>
    </tr>
  
  </table>
  
  <div class="actions">
    <%= link_to "Back to list", service_system_process_entities_path, class: "btn btn-link" %>
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>

<% end %>

app/views/process_entities/edit.html.erb
<h3>Editing process</h3>

<%= render 'form' %>

app/views/process_entities/index.html.erb
<h3>Processes</h3>

<%= link_to "New Process", new_service_system_process_entity_path, class: "btn btn-success" %>

<hr />

<% @process_entities.each do |process_entity| %>

<div class="well">
  <h4><%= link_to process_entity.label, service_system_process_entity_path(@service_system.id, process_entity.id) %></h4>

  <% if process_entity.bpmn_uri.present? %>
  <p>
    <strong>URI of BPMN description:</strong>
    <%= process_entity.bpmn_uri %>
  </p>
  <% end %>
  <% if process_entity.comment.present? %>
  <p>
    <%= process_entity.comment %>
  </p>
  <% end %>
</div>

<p>
  <%= link_to "Edit", edit_service_system_process_entity_path(@service_system.id, process_entity.id) %> |
  <%= link_to "Delete", service_system_process_entity_path(@service_system.id, process_entity.id), method: :delete, data: { confirm: "Are you sure you want to delete this?" } %>
</p>

<% end %>

app/views/process_entities/new.html.erb
<h3>New process</h3>

<%= render 'form' %>

app/views/process_entities/show.html.erb
<div class="well">
  <h3><%= @process_entity.label %></h3>

  <p>
    <strong>URI of BPMN description:</strong>
    <%= @process_entity.bpmn_uri %>
  </p>
  <% if @process_entity.comment.present? %>
  <p>
    <%= @process_entity.comment %>
  </p>
  <% end %>
</div>

<p>
  <%= link_to 'Back to list', service_system_process_entities_path, class: "btn btn-link" %>
  <%= link_to "Delete", service_system_process_entity_path(@service_system.id, @process_entity.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this?" } %>
  <%= link_to 'Edit', edit_service_system_process_entity_path(@service_system.id, @process_entity.id), class: "btn btn-success" %>
</p>