config/routes.rb
LssUsdlEditor::Application.routes.draw do

  resources :service_systems do

    resources :interactions do
      put "add_entity"
      delete "delete_entity"
      get "edit_time"
    end

    resources :business_entities
    resources :roles
    resources :goals
    resources :locations
    resources :process_entities, path: "processes"
    resources :resources

    get 'export_to_lss_usdl'
    get 'export_to_linked_usdl'

  end

  match "/service_systems/import" => "service_systems#import"

  devise_for :users

  root to: "service_systems#index"

end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  before_filter :select_tab

  def index
    if params[:view_status] and ["esb", "list"].index(params[:view_status])
      @service_system.view_status = params[:view_status]
      @service_system.save
    end

    @roles = Role.where "service_system_id = ?", @service_system.id
    @goals = Goal.where "service_system_id = ?", @service_system.id
    @locations = Location.where "service_system_id = ?", @service_system.id
    @processes = ProcessEntity.where "service_system_id = ?", @service_system.id
    @resources = Resource.where "service_system_id = ?", @service_system.id
    
    @filter = {
      roles: params[:roles],
      goals: params[:goals],
      locations: params[:locations],
      processes: params[:processes],
      resources: params[:resources]
    }
    if @service_system.view_status == "list"
      @interactions = Interaction.build_interactions_list(@service_system.id, @filter)
      @full_width = false
    else
      @interactions = Interaction.build_interactions_blueprint(@service_system.id, @filter)
      @full_width = true
    end

    respond_to do |format|
      format.html
      format.json { render json: @interactions }
    end
  end

  def show
    @interaction = Interaction.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @interaction }
    end
  end

  def new
    @interaction = @service_system.interactions.build
    @interactions_before_after = Interaction.where "service_system_id = ?", @service_system.id
    @interactions_during = @interactions_before_after

    respond_to do |format|
      format.html
      format.json { render json: @interaction }
    end
  end

  def edit
    @interaction = Interaction.find(params[:id])

    @roles = []
    Role.where("service_system_id = ?", @service_system.id).each do |obj|
      @roles.append obj unless @interaction.roles.index(obj)
    end
    @goals = []
    Goal.where("service_system_id = ?", @service_system.id).each do |obj|
      @goals.append obj unless @interaction.goals.index(obj)
    end
    @locations = []
    Location.where("service_system_id = ?", @service_system.id).each do |obj|
      @locations.append obj unless @interaction.locations.index(obj)
    end
    @processes = []
    ProcessEntity.where("service_system_id = ?", @service_system.id).each do |obj|
      @processes.append obj unless @interaction.processes.index(obj)
    end
    @resources = []
    Resource.where("service_system_id = ?", @service_system.id).each do |obj|
      @resources.append obj unless @interaction.resources.index(obj)
    end
    
    @interactions_before_after = Interaction.where "id != ? and service_system_id = ?", @interaction.id, @service_system.id
    @interactions_during = Interaction.where "id != ? and service_system_id = ? and interaction_type != ?", @interaction.id, @service_system.id, @interaction.interaction_type
  end

  def edit_time
    @interaction = Interaction.find(params[:interaction_id])
  end

  def create
    @interaction = Interaction.new(params[:interaction])
    @interaction.sid = camel_case @interaction.label
    @interaction.service_system = @service_system if @service_system.present?

    respond_to do |format|
      if @interaction.save
        format.html { redirect_to service_system_interactions_url, notice: 'Interaction was successfully created.' }
        format.json { render json: @interaction, status: :created, location: @interaction }
      else
        @interactions_before_after = Interaction.where "service_system_id = ?", @service_system.id
        @interactions_during = @interactions_before_after
        format.html { render action: "new" }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @interaction = Interaction.find(params[:id])
    params[:interaction][:sid] = camel_case params[:interaction][:label] if params[:interaction][:label].present?

    respond_to do |format|
      if @interaction.update_attributes(params[:interaction])
        format.html { redirect_to service_system_interaction_url, notice: 'Interaction was successfully updated.' }
        format.json { head :no_content }
      else   
        @interactions_before_after = Interaction.where "id != ? and service_system_id = ?", @interaction.id, @service_system.id
        @interactions_during = Interaction.where "id != ? and service_system_id = ? and interaction_type != ?", @interaction.id, @service_system.id, @interaction.interaction_type
        format.html { render action: "edit" }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_entity
    @interaction = Interaction.find(params[:interaction_id])
    if params[:role].present?
      @interaction.roles << Role.find(params[:role])
    elsif params[:goal].present?
      @interaction.goals << Goal.find(params[:goal])
    elsif params[:location].present?
      @interaction.locations << Location.find(params[:location])
    elsif params[:process].present?
      @interaction.processes << ProcessEntity.find(params[:process])
    elsif params[:resource].present?
      @interaction.received_resources << Resource.find(params[:resource]) if params[:relation] == "Receives"
      @interaction.created_resources << Resource.find(params[:resource]) if params[:relation] == "Creates"
      @interaction.consumed_resources << Resource.find(params[:resource]) if params[:relation] == "Consumes"
      @interaction.returned_resources << Resource.find(params[:resource]) if params[:relation] == "Returns"
    end

    respond_to do |format|
      if @interaction.save
        format.html { redirect_to service_system_interaction_url(@service_system.id, @interaction.id), notice: 'Interaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @interaction = Interaction.find(params[:id])
    @interaction.destroy

    respond_to do |format|
      format.html { redirect_to service_system_interactions_url }
      format.json { head :no_content }
    end
  end

  def delete_entity
    @interaction = Interaction.find(params[:interaction_id])
    if params[:role].present?
      @interaction.roles.delete(Role.find(params[:role]))
    elsif params[:goal].present?
      @interaction.goals.delete(Goal.find(params[:goal]))
    elsif params[:location].present?
      @interaction.locations.delete(Location.find(params[:location]))
    elsif params[:process].present?
      @interaction.processes.delete(ProcessEntity.find(params[:process]))
    elsif params[:received_resource].present?
      @interaction.received_resources.delete(Resource.find(params[:received_resource]))
    elsif params[:created_resource].present?
      @interaction.created_resources.delete(Resource.find(params[:created_resource]))
    elsif params[:consumed_resource].present?
      @interaction.consumed_resources.delete(Resource.find(params[:consumed_resource]))
    elsif params[:returned_resource].present?
      @interaction.returned_resources.delete(Resource.find(params[:returned_resource]))
    end

    respond_to do |format|
      format.html { redirect_to service_system_interaction_url(@service_system.id, @interaction.id), notice: 'Interaction was successfully updated.' }
      format.json { head :no_content }
    end
  end

  private

  def select_tab
    @tab = {"interactions" => true}
  end
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/views/interactions/edit.html.erb
<h3>Editing interaction "<%= @interaction.label %>"</h3>

<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">
      Metadata
    </a></li>
    <li><a href="#tab2" data-toggle="tab">
      <i class="icon-user"></i>
      Roles<% if @interaction.roles.size > 0 %> (<%= @interaction.roles.size %>)<% end %>
    </a></li>
    <li><a href="#tab3" data-toggle="tab">
      <i class="icon-time"></i>
      Time
    </a></li>
    <li><a href="#tab4" data-toggle="tab">
      <i class="icon-screenshot"></i>
      Goals<% if @interaction.goals.size > 0 %> (<%= @interaction.goals.size %>)<% end %>
    </a></li>
    <li><a href="#tab5" data-toggle="tab">
      <i class="icon-globe"></i>
      Locations<% if @interaction.locations.size > 0 %> (<%= @interaction.locations.size %>)<% end %>
    </a></li>
    <li><a href="#tab6" data-toggle="tab">
      <i class="icon-tasks"></i>
      Processes<% if @interaction.processes.size > 0 %> (<%= @interaction.processes.size %>)<% end %>
    </a></li>
    <li><a href="#tab7" data-toggle="tab">
      <i class="icon-book"></i>
      Resources<% if @interaction.resources.size > 0 %> (<%= @interaction.resources.size %>)<% end %>
    </a></li>
  </ul>
  <div class="tab-content">

    <%# Metadata %>
    <div class="tab-pane active" id="tab1">
      <%= render 'form' %>
    </div>

    <%# Roles %>
    <div class="tab-pane" id="tab2">
      <table class="table table-striped">
        <% for role in @interaction.roles %>
          <tr><td>
            <%= form_tag(service_system_interaction_delete_entity_path(@service_system.id, @interaction.id), method: :delete, style: "margin: 0") do %>
              <%= link_to role.label, service_system_role_path(@service_system.id, role.id) %>
              <%= hidden_field_tag "role", role.id %>
              (<%= submit_tag "Remove", class: "btn btn-link" %>)
            <% end %>
          </td></tr>
        <% end %>
      </table>
      <%= form_tag(service_system_interaction_add_entity_path(@service_system.id, @interaction.id), method: :put) do %>
        <%= select_tag "role", options_from_collection_for_select(@roles, "id", "label"), include_blank: true %>
        <%= submit_tag "Add role to this interaction", class: "btn btn-success" %>
      <% end %>
    </div>

    <%# Time %>
    <div class="tab-pane" id="tab3">
      <p>
        <strong>Time description:</strong>
        <%= @interaction.time_description %>
      </p>
      <p>
        <strong>Duration:</strong>
        <%= @interaction.duration_description %>
      </p>
      <p>
        <%= link_to 'Edit time data', service_system_interaction_edit_time_path(@service_system.id, @interaction.id), class: "btn btn-success" %>
      </p>
    </div>

    <%# Goals %>
    <div class="tab-pane" id="tab4">
      <table class="table table-striped">
        <% for goal in @interaction.goals %>
          <tr><td>
            <%= form_tag(service_system_interaction_delete_entity_path(@service_system.id, @interaction.id), method: :delete, style: "margin: 0") do %>
              <%= link_to goal.label, service_system_goal_path(@service_system.id, goal.id) %>
              <%= hidden_field_tag "goal", goal.id %>
              (<%= submit_tag "Remove", class: "btn btn-link" %>)
            <% end %>
          </td></tr>
        <% end %>
      </table>
      <%= form_tag(service_system_interaction_add_entity_path(@service_system.id, @interaction.id), method: :put) do %>
        <%= select_tag "goal", options_from_collection_for_select(@goals, "id", "label"), include_blank: true %>
        <%= submit_tag "Add goal to this interaction", class: "btn btn-success" %>
      <% end %>
    </div>

    <%# Locations %>
    <div class="tab-pane" id="tab5">
      <table class="table table-striped">
        <% for location in @interaction.locations %>
          <tr><td>
            <%= form_tag(service_system_interaction_delete_entity_path(@service_system.id, @interaction.id), method: :delete, style: "margin: 0") do %>
              <%= link_to location.label, service_system_location_path(@service_system.id, location.id) %>
              <%= hidden_field_tag "location", location.id %>
              (<%= submit_tag "Remove", class: "btn btn-link" %>)
            <% end %>
          </td></tr>
        <% end %>
      </table>
      <%= form_tag(service_system_interaction_add_entity_path(@service_system.id, @interaction.id), method: :put) do %>
        <%= select_tag "location", options_from_collection_for_select(@locations, "id", "label"), include_blank: true %>
        <%= submit_tag "Add location to this interaction", class: "btn btn-success" %>
      <% end %>
    </div>

    <%# Processes %>
    <div class="tab-pane" id="tab6">
      <table class="table table-striped">
        <% for process in @interaction.processes %>
          <tr><td>
            <%= form_tag(service_system_interaction_delete_entity_path(@service_system.id, @interaction.id), method: :delete, style: "margin: 0") do %>
              <%= link_to process.label, service_system_process_entity_path(@service_system.id, process.id) %>
              <%= hidden_field_tag "process", process.id %>
              (<%= submit_tag "Remove", class: "btn btn-link" %>)
            <% end %>
          </td></tr>
        <% end %>
      </table>
      <%= form_tag(service_system_interaction_add_entity_path(@service_system.id, @interaction.id), method: :put) do %>
        <%= select_tag "process", options_from_collection_for_select(@processes, "id", "label"), include_blank: true %>
        <%= submit_tag "Add process to this interaction", class: "btn btn-success" %>
      <% end %>
    </div>

    <%# Resources %>
    <div class="tab-pane" id="tab7">
      <table class="table table-striped">
        <% for resource in @interaction.received_resources %>
          <tr>
            <td>Receives</td>
            <td>
            <%= form_tag(service_system_interaction_delete_entity_path(@service_system.id, @interaction.id), method: :delete, style: "margin: 0") do %>
              <%= link_to resource.label, service_system_resource_path(@service_system.id, resource.id) %>
              <%= hidden_field_tag "received_resource", resource.id %>
              (<%= submit_tag "Remove", class: "btn btn-link" %>)
            <% end %>
          </td></tr>
        <% end %>
        <% for resource in @interaction.created_resources %>
          <tr>
            <td>Creates</td>
            <td>
            <%= form_tag(service_system_interaction_delete_entity_path(@service_system.id, @interaction.id), method: :delete, style: "margin: 0") do %>
              <%= link_to resource.label, service_system_resource_path(@service_system.id, resource.id) %>
              <%= hidden_field_tag "created_resource", resource.id %>
              (<%= submit_tag "Remove", class: "btn btn-link" %>)
            <% end %>
          </td></tr>
        <% end %>
        <% for resource in @interaction.consumed_resources %>
          <tr>
            <td>Consumes</td>
            <td>
            <%= form_tag(service_system_interaction_delete_entity_path(@service_system.id, @interaction.id), method: :delete, style: "margin: 0") do %>
              <%= link_to resource.label, service_system_resource_path(@service_system.id, resource.id) %>
              <%= hidden_field_tag "consumed_resource", resource.id %>
              (<%= submit_tag "Remove", class: "btn btn-link" %>)
            <% end %>
          </td></tr>
        <% end %>
        <% for resource in @interaction.returned_resources %>
          <tr>
            <td>Returns</td>
            <td>
            <%= form_tag(service_system_interaction_delete_entity_path(@service_system.id, @interaction.id), method: :delete, style: "margin: 0") do %>
              <%= link_to resource.label, service_system_resource_path(@service_system.id, resource.id) %>
              <%= hidden_field_tag "returned_resource", resource.id %>
              (<%= submit_tag "Remove", class: "btn btn-link" %>)
            <% end %>
          </td></tr>
        <% end %>
      </table>
      <%= form_tag(service_system_interaction_add_entity_path(@service_system.id, @interaction.id), method: :put) do %>
        <%= select_tag "relation", options_for_select(["Receives", "Creates", "Consumes", "Returns"]) %>
        <%= select_tag "resource", options_from_collection_for_select(@resources, "id", "label"), include_blank: true %>
        <%= submit_tag "Add resource to this interaction", class: "btn btn-success" %>
      <% end %>
    </div>

  </div>
</div>

app/views/interactions/index.html.erb
<div id="service-metadata">
  <div class="row service-data">
    <div class="span8">
      <span class="code">
        <% if @service_system.prefix.present? %><%= @service_system.prefix %>: <% end %>
        &lt;<%= @service_system.uri %>&gt;
      </span>
      <p><%= @service_system.comment %></p>
    </div>
    <div class="span4">
      <a href="#" class="btn toggle-interactions-menu"><i class="icon-list-alt"></i> Show menu</a>
      <%= link_to "New Interaction", new_service_system_interaction_path, class: 'btn btn-success' %>
    </div>
  </div>
  <div class="slide-menu">
    <div class="row">
      <div class="span12">
        <%= link_to 'Edit metadata', edit_service_system_path(@service_system), class: "btn btn-success" %>
        <div class="btn-group">
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-eye-open"></i> View interactions as <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li<% if @full_width %> class="active"<% end %>><a href="?view_status=esb">Extended service blueprint</a></li>
            <li<% if not @full_width %> class="active"<% end %>><a href="?view_status=list">Plain list</a></li>
          </ul>
        </div>
        <div class="btn-group">
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-download-alt"></i> Export <% if @filter.select { |k,v| v.present? }.present? %> filtered <% end %>data to <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'LSS-USDL file', service_system_export_to_lss_usdl_path(@service_system, :filter => @filter), target: "_blank" %></li>
            <li><%= link_to 'Linked USDL file', service_system_export_to_linked_usdl_path(@service_system, :filter => @filter), target: "_blank" %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <hr />
        <%= form_tag("/service_systems/#{@service_system.id}/interactions", method: :get, id: 'filter-form', class: "form-inline") do %>
          <%= select_tag :roles, options_from_collection_for_select(@roles, "id", "label", @filter[:roles]), prompt: "All roles", class: "span4" %>
          <%= select_tag :goals, options_from_collection_for_select(@goals, "id", "label", @filter[:goals]), prompt: "All goals", class: "span4" %>
          <%= select_tag :locations, options_from_collection_for_select(@locations, "id", "label", @filter[:locations]), prompt: "All locations", class: "span4" %>
          <%= select_tag :processes, options_from_collection_for_select(@processes, "id", "label", @filter[:processes]), prompt: "All processes", class: "span4" %>
          <%= select_tag :resources, options_from_collection_for_select(@resources, "id", "label", @filter[:resources]), prompt: "All resources", class: "span4" %>
          <%= link_to 'Clear filters', service_system_interactions_path(@service_system), class: "btn", style: "margin: -10px 0 0 105px" %>
          <%= submit_tag "Apply filter", class: "btn btn-primary", style: "margin-top: -10px" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if @full_width %>

  <div id="blueprint">

    <table id="interactions-table">
      <tr>
        <td><p class="subtitle">Line of interaction</p></td>
        <% for interaction in @interactions[0] %>
          <td><%= render 'blueprint_node', interaction: interaction %></td>
        <% end %>
      </tr>
      <tr>
        <td><p class="subtitle">Line of visibility</p></td>
        <% for interaction in @interactions[1] %>
          <td><%= render 'blueprint_node', interaction: interaction %></td>
        <% end %>
      </tr>
      <tr>
        <td><p class="subtitle">Line of internal interaction</p></td>
        <% for interaction in @interactions[2] %>
          <td><%= render 'blueprint_node', interaction: interaction %></td>
        <% end %>
      </tr>
      <tr>
        <td></td>
        <% for interaction in @interactions[3] %>
          <td><%= render 'blueprint_node', interaction: interaction %></td>
        <% end %>
      </tr>
    </table>

  </div>

<% else %>

<div class="interactions-list">

  <% @interactions.each do |interaction| %>

    <div class="well">
      <h4><%= link_to interaction.label, service_system_interaction_path(@service_system.id, interaction.id) %></h4>

      <% if interaction.interaction_type.present? %>
      <p>
        <strong>Interaction type:</strong>
        <%= interaction.interaction_type.gsub /Interaction/, " interaction" %>
      </p>
      <% end %>
      <% if interaction.roles.present? %>
      <p>
        <strong>Roles:</strong>
        <% interaction.roles.each do |role| %>
          <span class="label">
            <a href="<%= service_system_role_path(@service_system.id, role.id) %>">
              <i class="icon-user icon-white"></i>
              <%= role %>
            </a>
          </span>
        <% end %>
      </p>
      <% end %>
      <% if interaction.time_string.present? %>
      <p>
        <strong>Time:</strong>
        <span class="label">
          <a href="<%= service_system_interaction_path(@service_system.id, interaction.id) %>">
            <i class="icon-time icon-white"></i>
            <%= interaction.time_string %>
          </a>
        </span>
      </p>
      <% end %>
      <% if interaction.goals.present? %>
      <p>
        <strong>Goals:</strong>
        <% interaction.goals.each do |goal| %>
          <span class="label label-info">
            <a href="<%= service_system_goal_path(@service_system.id, goal.id) %>">
              <i class="icon-screenshot icon-white"></i>
              <%= goal %>
            </a>
          </span>
        <% end %>
      </p>
      <% end %>
      <% if interaction.locations.present? %>
      <p>
        <strong>Locations:</strong>
        <% interaction.locations.each do |location| %>
          <span class="label">
            <a href="<%= service_system_location_path(@service_system.id, location.id) %>">
              <i class="icon-globe icon-white"></i>
              <%= location %>
            </a>
          </span>
        <% end %>
      </p>
      <% end %>
      <% if interaction.processes.present? %>
      <p>
        <strong>Processes:</strong>
        <% interaction.processes.each do |process| %>
          <span class="label">
            <a href="<%= service_system_process_entity_path(@service_system.id, process.id) %>">
              <i class="icon-tasks icon-white"></i>
              <%= process %>
            </a>
          </span>
        <% end %>
      </p>
      <% end %>
      <% if interaction.received_resources.present? %>
      <p>
        <strong>Received resources:</strong>
        <% interaction.received_resources.each do |resource| %>
          <span class="label label-warning">
            <a href="<%= service_system_resource_path(@service_system.id, resource.id) %>">
              <i class="icon-arrow-down icon-white"></i>
              <i class="icon-book icon-white"></i>
              <%= resource %>
            </a>
          </span>
        <% end %>
      </p>
      <% end %>
      <% if interaction.created_resources.present? %>
      <p>
        <strong>Created resources:</strong>
        <% interaction.created_resources.each do |resource| %>
          <span class="label label-success">
            <a href="<%= service_system_resource_path(@service_system.id, resource.id) %>" data-toggle="tooltip" title="Creates resource: <%= resource %>">
              <i class="icon-arrow-down icon-white"></i>
              <i class="icon-book icon-white"></i>
              <%= resource %>
            </a>
          </span>
        <% end %>
      </p>
      <% end %>
      <% if interaction.consumed_resources.present? %>
      <p>
        <strong>Consumed resources:</strong>
        <% interaction.consumed_resources.each do |resource| %>
          <span class="label label-important">
            <a href="<%= service_system_resource_path(@service_system.id, resource.id) %>" data-toggle="tooltip" title="Consumes resource: <%= resource %>">
              <i class="icon-arrow-up icon-white"></i>
              <i class="icon-book icon-white"></i>
              <%= resource %>
            </a>
          </span>
        <% end %>
      </p>
      <% end %>
      <% if interaction.returned_resources.present? %>
      <p>
        <strong>Returned resources:</strong>
        <% interaction.returned_resources.each do |resource| %>
          <span class="label label-warning">
            <a href="<%= service_system_resource_path(@service_system.id, resource.id) %>" data-toggle="tooltip" title="Returns resource: <%= resource %>">
              <i class="icon-arrow-up icon-white"></i>
              <i class="icon-book icon-white"></i>
              <%= resource %>
            </a>
          </span>
        <% end %>
      </p>
      <% end %>
      <% if interaction.comment.present? %>
      <p>
        <%= interaction.comment %>
      </p>
      <% end %>

      <p>
        <%= link_to "Edit", edit_service_system_interaction_path(@service_system.id, interaction.id) %> |
        <%= link_to "Delete", service_system_interaction_path(@service_system.id, interaction.id), method: :delete, data: { confirm: "Are you sure you want to delete this?" } %>
      </p>
    </div>

  <% end %>

</div>

<% end %>

app/views/interactions/new.html.erb
<h3>New interaction</h3>

<%= render 'form' %>

app/views/interactions/show.html.erb
<div class="well">
  <h3><%= @interaction.label %></h3>

  <% if @interaction.interaction_type.present? %>
  <p>
    <strong>Interaction type:</strong>
    <%= @interaction.interaction_type.gsub /Interaction/, " interaction" %>
  </p>
  <% end %>
  <% if @interaction.roles.present? %>
  <p>
    <strong>Roles:</strong>
    <% @interaction.roles.each do |role| %>
      <span class="label">
        <a href="<%= service_system_role_path(@service_system.id, role.id) %>">
          <i class="icon-user icon-white"></i>
          <%= role %>
        </a>
      </span>
    <% end %>
  </p>
  <% end %>
  <% if @interaction.time_string.present? %>
  <p>
    <strong>Time:</strong>
    <span class="label">
      <a href="<%= service_system_interaction_path(@service_system.id, @interaction.id) %>">
        <i class="icon-time icon-white"></i>
        <%= @interaction.time_string %>
      </a>
    </span>
  </p>
  <% end %>
  <% if @interaction.goals.present? %>
  <p>
    <strong>Goals:</strong>
    <% @interaction.goals.each do |goal| %>
      <span class="label label-info">
        <a href="<%= service_system_goal_path(@service_system.id, goal.id) %>">
          <i class="icon-screenshot icon-white"></i>
          <%= goal %>
        </a>
      </span>
    <% end %>
  </p>
  <% end %>
  <% if @interaction.locations.present? %>
  <p>
    <strong>Locations:</strong>
    <% @interaction.locations.each do |location| %>
      <span class="label">
        <a href="<%= service_system_location_path(@service_system.id, location.id) %>">
          <i class="icon-globe icon-white"></i>
          <%= location %>
        </a>
      </span>
    <% end %>
  </p>
  <% end %>
  <% if @interaction.processes.present? %>
  <p>
    <strong>Processes:</strong>
    <% @interaction.processes.each do |process| %>
      <span class="label">
        <a href="<%= service_system_process_entity_path(@service_system.id, process.id) %>">
          <i class="icon-tasks icon-white"></i>
          <%= process %>
        </a>
      </span>
    <% end %>
  </p>
  <% end %>
  <% if @interaction.received_resources.present? %>
  <p>
    <strong>Received resources:</strong>
    <% @interaction.received_resources.each do |resource| %>
      <span class="label label-warning">
        <a href="<%= service_system_resource_path(@service_system.id, resource.id) %>">
          <i class="icon-arrow-down icon-white"></i>
          <i class="icon-book icon-white"></i>
          <%= resource %>
        </a>
      </span>
    <% end %>
  </p>
  <% end %>
  <% if @interaction.created_resources.present? %>
  <p>
    <strong>Created resources:</strong>
    <% @interaction.created_resources.each do |resource| %>
      <span class="label label-success">
        <a href="<%= service_system_resource_path(@service_system.id, resource.id) %>" data-toggle="tooltip" title="Creates resource: <%= resource %>">
          <i class="icon-arrow-down icon-white"></i>
          <i class="icon-book icon-white"></i>
          <%= resource %>
        </a>
      </span>
    <% end %>
  </p>
  <% end %>
  <% if @interaction.consumed_resources.present? %>
  <p>
    <strong>Consumed resources:</strong>
    <% @interaction.consumed_resources.each do |resource| %>
      <span class="label label-important">
        <a href="<%= service_system_resource_path(@service_system.id, resource.id) %>" data-toggle="tooltip" title="Consumes resource: <%= resource %>">
          <i class="icon-arrow-up icon-white"></i>
          <i class="icon-book icon-white"></i>
          <%= resource %>
        </a>
      </span>
    <% end %>
  </p>
  <% end %>
  <% if @interaction.returned_resources.present? %>
  <p>
    <strong>Returned resources:</strong>
    <% @interaction.returned_resources.each do |resource| %>
      <span class="label label-warning">
        <a href="<%= service_system_resource_path(@service_system.id, resource.id) %>" data-toggle="tooltip" title="Returns resource: <%= resource %>">
          <i class="icon-arrow-up icon-white"></i>
          <i class="icon-book icon-white"></i>
          <%= resource %>
        </a>
      </span>
    <% end %>
  </p>
  <% end %>
  <% if @interaction.comment.present? %>
  <p>
    <%= @interaction.comment %>
  </p>
  <% end %>
</div>

<p>
  <%= link_to 'Back to list', service_system_interactions_path, class: "btn btn-link" %>
  <%= link_to "Delete", service_system_interaction_path(@service_system.id, @interaction.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this?" } %>
  <%= link_to 'Edit', edit_service_system_interaction_path(@service_system.id, @interaction.id), class: "btn btn-success" %>
</p>