config/routes.rb
LssUsdlEditor::Application.routes.draw do

  resources :service_systems do

    resources :interactions do
      put "add_entity"
      delete "delete_entity"
      get "edit_time"
    end

    resources :business_entities
    resources :roles
    resources :goals
    resources :locations
    resources :process_entities, path: "processes"
    resources :resources

    get 'export_to_lss_usdl'
    get 'export_to_linked_usdl'

  end

  match "/service_systems/import" => "service_systems#import"

  devise_for :users

  root to: "service_systems#index"

end

app/views/resources/_form.html.erb
<%= form_for [@service_system, @resource] do |f| %>

  <% if @resource.errors.any? %>
    <div id="error-explanation">
      <h4><%= pluralize @resource.errors.count, "error" %> prevented this resource from being saved:</h4>
      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table>
  
    <tr>
      <td><%= f.label :label %></td>
      <td><%= f.text_field :label, class: "span5" %></td>
    </tr>
  
    <tr>
      <td><%= f.label :resource_type %></td>
      <td><%= f.select :resource_type, Resource.subclasses.map{ |sc| ["#{sc} resource", "#{sc}Resource"] }.prepend(["--", "--"]) %></td>
    </tr>
  
    <tr>
      <td><%= f.label :dbpedia_resource, "DBpedia resource" %></td>
      <td><%= f.text_field :dbpedia_resource, class: "span5" %></td>
    </tr>
  
    <tr>
      <td><%= f.label :value %></td>
      <td><%= f.text_field :value, class: "span5" %></td>
    </tr>
  
    <tr>
      <td><%= f.label :max_value %></td>
      <td><%= f.text_field :max_value, class: "span5" %></td>
    </tr>
  
    <tr>
      <td><%= f.label :min_value %></td>
      <td><%= f.text_field :min_value, class: "span5" %></td>
    </tr>
  
    <tr>
      <td><%= f.label :unit_of_measurement %></td>
      <td><%= f.text_field :unit_of_measurement, class: "span5" %></td>
    </tr>
  
    <tr>
      <td><%= f.label :comment %></td>
      <td><%= f.text_area :comment, class: "span5", rows: "3" %></td>
    </tr>
  
  </table>
  
  <div class="actions">
    <%= link_to "Back to list", service_system_resources_path, class: "btn btn-link" %>
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>

<% end %>

app/views/resources/edit.html.erb
<h3>Editing resource</h3>

<%= render 'form' %>

app/views/resources/index.html.erb
<h3>Resources</h3>

<%= link_to "New Resource", new_service_system_resource_path, class: "btn btn-success" %>

<hr />

<% @resources.each do |resource| %>

<div class="well">
  <h4><%= link_to resource.label, service_system_resource_path(@service_system.id, resource.id) %></h4>

  <% if resource.dbpedia_resource.present? %>
  <p>
    <strong>DBpedia resource:</strong>
    <a href="<%= resource.dbpedia_resource %>" target="_blank"><%= resource.dbpedia_resource.gsub(/^.*\//, '') %></a>
  </p>
  <% end %>
  <% if resource.value %>
  <p>
    <strong>Value:</strong>
    <%= resource.value_ %> <%= resource.unit_of_measurement %>
  </p>
  <% end %>
  <% if resource.max_value %>
  <p>
    <strong>Max value:</strong>
    <%= resource.max_value_ %> <%= resource.unit_of_measurement %>
  </p>
  <% end %>
  <% if resource.min_value %>
  <p>
    <strong>Min value:</strong>
    <%= resource.min_value_ %> <%= resource.unit_of_measurement %>
  </p>
  <% end %>
  <% if resource.resource_type.present? %>
  <p>
    <strong>Resource type:</strong>
    <%= resource.resource_type.gsub(/Resource/, " resource") %>
  </p>
  <% end %>
  <% if resource.comment %>
  <p>
    <%= resource.comment %>
  </p>
  <% end %>

  <p>
    <%= link_to "Edit", edit_service_system_resource_path(@service_system.id, resource.id) %> |
    <%= link_to "Delete", service_system_resource_path(@service_system.id, resource.id), method: :delete, data: { confirm: "Are you sure you want to delete this?" } %>
  </p>
</div>

<% end %>

app/views/resources/new.html.erb
<h3>New resource</h3>

<%= render 'form' %>

app/views/resources/show.html.erb
<div class="well">
  <h3><%= @resource.label %></h3>

  <% if @resource.dbpedia_resource.present? %>
  <p>
    <strong>DBpedia resource:</strong>
    <a href="<%= @resource.dbpedia_resource %>" target="_blank"><%= @resource.dbpedia_resource.gsub(/^.*\//, '') %></a>
  </p>
  <% end %>
  <% if @resource.value %>
  <p>
    <strong>Value:</strong>
    <%= @resource.value_ %> <%= @resource.unit_of_measurement %>
  </p>
  <% end %>
  <% if @resource.max_value %>
  <p>
    <strong>Max value:</strong>
    <%= @resource.max_value_ %> <%= @resource.unit_of_measurement %>
  </p>
  <% end %>
  <% if @resource.min_value %>
  <p>
    <strong>Min value:</strong>
    <%= @resource.min_value_ %> <%= @resource.unit_of_measurement %>
  </p>
  <% end %>
  <% if @resource.resource_type.present? %>
  <p>
    <strong>Resource type:</strong>
    <%= @resource.resource_type.gsub(/Resource/, " resource") %>
  </p>
  <% end %>
  <% if @resource.comment.present? %>
  <p>
    <strong>Comment:</strong><br />
    <%= @resource.comment %>
  </p>
  <% end %>
</div>

<p>
  <%= link_to 'Back to list', service_system_resources_path, class: "btn btn-link" %>
  <%= link_to "Delete", service_system_resource_path(@service_system.id, @resource.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this?" } %>
  <%= link_to 'Edit', edit_service_system_resource_path(@service_system.id, @resource.id), class: "btn btn-success" %>
</p>