config/routes.rb
LssUsdlEditor::Application.routes.draw do

  resources :service_systems do

    resources :interactions do
      put "add_entity"
      delete "delete_entity"
      get "edit_time"
    end

    resources :business_entities
    resources :roles
    resources :goals
    resources :locations
    resources :process_entities, path: "processes"
    resources :resources

    get 'export_to_lss_usdl'
    get 'export_to_linked_usdl'

  end

  match "/service_systems/import" => "service_systems#import"

  devise_for :users

  root to: "service_systems#index"

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :comment, :label, :business_entity_id, :service_system_id, :sid
  belongs_to :service_system
  belongs_to :business_entity
  has_and_belongs_to_many :interactions

  validates :label, :sid, presence: true
  validates :business_entity_id, numericality: { only_integer: true }, allow_nil: true
  validates :service_system_id, numericality: { only_integer: true }

  def to_s
    self.label
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :select_tab

  def index
    if @service_system.present?
      @roles = Role.where "service_system_id = ?", @service_system.id
    else
      @roles = Role.all
    end

    respond_to do |format|
      format.html
      format.json { render json: @roles }
    end
  end

  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @role }
    end
  end

  def new
    @role = @service_system.roles.build
    @business_entities = BusinessEntity.where "service_system_id = ?", @service_system.id

    respond_to do |format|
      format.html
      format.json { render json: @role }
    end
  end

  def edit
    @role = Role.find(params[:id])
    @business_entities = BusinessEntity.where "service_system_id = ?", @service_system.id
  end

  def create
    @role = Role.new(params[:role])
    @role.sid = camel_case @role.label
    @role.service_system = @service_system if @service_system.present?

    respond_to do |format|
      if @role.save
        format.html { redirect_to service_system_roles_url, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @role = Role.find(params[:id])
    params[:role][:sid] = camel_case params[:role][:label]

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to service_system_role_url, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to service_system_roles_url }
      format.json { head :no_content }
    end
  end

  private

  def select_tab
    @tab = {"roles" => true}
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for [@service_system, @role] do |f| %>

  <% if @role.errors.any? %>
    <div id="error-explanation">
      <h4><%= pluralize @role.errors.count, "error" %> prevented this role from being saved:</h4>
      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table>
  
    <tr>
      <td><%= f.label :label %></td>
      <td><%= f.text_field :label, class: "span5" %></td>
    </tr>

    <tr>
      <td><%= f.label :business_entity_id, "Business entity" %></td>
      <td><%= f.select :business_entity_id, @business_entities.map{ |be| [be.foaf_name, be.id] }.prepend(["--", nil]) %></td>
    </tr>
  
    <tr>
      <td><%= f.label :comment %></td>
      <td><%= f.text_area :comment, class: "span5", rows: "3" %></td>
    </tr>
  
  </table>
  
  <div class="actions">
    <%= link_to "Back to list", service_system_roles_path, class: "btn btn-link" %>
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>

<% end %>

app/views/roles/edit.html.erb
<h3>Editing role</h3>

<%= render 'form' %>

app/views/roles/index.html.erb
<h3>Roles</h3>

<%= link_to "New Role", new_service_system_role_path, class: "btn btn-success" %>

<hr />

<% @roles.each do |role| %>

<div class="well">
  <h4><%= link_to role.label, service_system_role_path(@service_system.id, role.id) %></h4>

  <% if role.business_entity %>
  <p>
    <strong>Business entity:</strong>
    <%= link_to role.business_entity, service_system_business_entity_path(@service_system.id, role.business_entity.id) %>
  </p>
  <% end %>
  <% if role.comment.present? %>
  <p>
    <%= role.comment %>
  </p>
  <% end %>

  <p>
    <%= link_to "Edit", edit_service_system_role_path(@service_system.id, role.id) %> |
    <%= link_to "Delete", service_system_role_path(@service_system.id, role.id), method: :delete, data: { confirm: "Are you sure you want to delete this?" } %>
  </p>
</div>

<% end %>

app/views/roles/new.html.erb
<h3>New role</h3>

<%= render 'form' %>

app/views/roles/show.html.erb
<div class="well">
  <h3><%= @role.label %></h3>

  <% if @role.business_entity %>
  <p>
    <strong>Business entity:</strong>
    <%= link_to @role.business_entity, service_system_business_entity_path(@service_system.id, @role.business_entity.id) %>
  </p>
  <% end %>
  <% if @role.comment %>
  <p>
    <%= @role.comment %>
  </p>
  <% end %>
</div>

<p>
  <%= link_to 'Back to list', service_system_roles_path, class: "btn btn-link" %>
  <%= link_to "Delete", service_system_role_path(@service_system.id, @role.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this?" } %>
  <%= link_to 'Edit', edit_service_system_role_path(@service_system.id, @role.id), class: "btn btn-success" %>
</p>